### ISSUE TITLE
lineMerge ?

### ISSUE THREAD

**Issue by nraynaud** [JuliaGeo/LibGEOS.jl#108]
it seems that lineMerge is not exposed in the operations file, is there a reason? 
do you have a workaround?

thank you for your work.

**Comment by visr** [comment]
I don't think there is a reason no. It would be good to add, similar to how recently these were added for example: cc698161c9358a767a084e613e6886bb1b8c520e.

But you can always directly call the lower level functions. I didn't try this, but I think this should work:
```julia
LibGEOS.geomFromGEOS(LibGEOS.GEOSLineMerge_r(LibGEOS._context, g.ptr))
```

**Comment by nraynaud** [comment]
Thank you very much. I discovered this lower layer layer in the day.

I have some experience in GIS, but I am learning Julia, so everything is incredibly hard, I have to try array formats, constructors and other overloaded things for everything.

Do you know of an open source project using your library?

When I’m on the computer I’ll post a lower level example here as a breadcrumb for people coming with the same question, then I’ll close this issue.

Thank you for your work.

Envoyé de mon iPhone

**Comment by visr** [comment]
Yeah, since the documentation is still quite limited, it helps to look around in the code and tests, though that's not as straightforward.

Open source dependants can in general be seen here; there are not many: https://juliahub.com/ui/Packages/LibGEOS/we91k/0.6.9?page=2

You can also try out https://yeesian.com/ArchGDAL.jl/dev/geometries/. It also uses GEOS, and that library has seen more maintenance, and has better documentation.

**Comment by nraynaud** [comment]
thank you very much for thoses pointers.
Sorry for my comment that ignored your example, I didn't see it on my phone.
the exact syntax I used is this:
```
result  = LibGEOS.MultiLineString(LibGEOS.lineMerge(f_multilinestring.ptr))
```
