### ISSUE TITLE
GEOSCoordSeq_isCCW_r() seems to have wrong parameter type

### ISSUE THREAD

**Issue by nraynaud** [JuliaGeo/LibGEOS.jl#110]
Hi, I'm a beginner at julia, so apologies if I'm wrong.

The last parameter to `GEOSCoordSeq_isCCW_r()` in the C API is an output boolean parameter called `is_ccw` and declared `char*` .
It got translated to `Cstring` in julia, but by my understanding this is an error because `Cstring` can't have a null byte in their buffer, and GEOSCoordSeq_isCCW_r() will want to write 0 if the path is not CCW.

I think a `Ptr{UInt8}` was warranted in this case.

thank you for your good work.

julia API:
https://github.com/JuliaGeo/LibGEOS.jl/blob/8449e4c99bd911a067bd564e21c8e820a4771fd2/src/libgeos_api.jl#L319
C API:
https://libgeos.org/doxygen/geos__c_8h.html#a8f4d265d599fbd41f4149fcf81095b1a

**Comment by visr** [comment]
Wow I had no idea `char*` is sometimes used as a boolean.

Do you maybe have a runnable example that demonstrates the issue? And have you tried to change `is_ccw::Cstring` to `is_ccw::Bool`? Maybe it needs to be `Ptr{Bool}` actually.

Since the API is auto-generated, we would have to add this to https://github.com/JuliaGeo/LibGEOS.jl/blob/8449e4c99bd911a067bd564e21c8e820a4771fd2/gen/generator.jl#L15.

**Comment by nraynaud** [comment]
Sorry, I tried to fiddle a bit with the C layer, got a few signal 11 craches and then the CTO informed me that we have a polygon orientation test in the codebase anyways, and I stopped chasing this issue.

I think 2 weeks of julia is a bit early for meddling with the foreign function interface of a GC language.

**Comment by evetion** [comment]
Well, according to the manual `Cstrings are NUL-terminated.` So it works fine as it is. I've exposed the isCCW functionality in the linked PR.
