### ISSUE TITLE
Convert from LinearRing to Polygon/MultiPolygon 

### ISSUE THREAD

**Issue by skygering** [JuliaGeo/LibGEOS.jl#129]
I am trying to take the exterior ring of a polygon or multipolygon and convert that LinearRing be a polygon itself, effectively removing the hole from a polygon. For example:
`poly = LibGEOS.readgeom("POLYGON((0 0, 4 0, 4 4, 0 4, 0 0), (1 1, 1 2, 2 2, 2 1, 1 1))")`
`hole = GeoInterface.getgeom(hpoly, 2)`
`hole_poly = convert(LibGEOS.Polygon, hole)`

However, when I do this I get an error, which I have attached below. The  error basically says to create an issue, which is why I am! :) 
![Screen Shot 2022-09-02 at 4 11 23 PM](https://user-images.githubusercontent.com/60117338/188245722-e2e7d83e-15fd-4a3b-809a-7fac5e180b96.png)

I have a way around this using the same hole as above:
`
coordpoly = Polygon([GeoInterface.coordinates(hole)])
`
Would this basically be the code needed for the convert function to work within the package? If so, I can try to fix it and do a pull request.

**Comment by yeesian** [comment]
> Would this basically be the code needed for the convert function to work within the package? If so, I can try to fix it and do a pull request.

Yes, I think that will be great! It does make sense for what the intuitive behavior would be if we wanted to convert a linear ring to a polygon (i.e. it would correspond to the outermost ring, and form a polygon with no holes).

**Comment by evetion** [comment]
Thanks for creating an issue! 👍🏻 

We didn't consider this use-case when designing GeoInterface, we thought about conversion between different custom geometries, with the same geomtrait. The error message is about raising an issue because the package didn't an implement a conversion for LinearRingTrait at all.

I'm not sure if convert should convert between geometry types/traits, is a LinearRing representable as Polygon (yes? I guess, but not (always?) the other way around?). It's hard to create a good fallback in GeoInterface for such conversions, so it would depend on the package implementations.

In the meantime, what we could do as well is to create more methods for `Polygon/createPolygon`, as the only non GeoInterface way is `LibGEOS.createPolygon(hole.ptr, Ptr{Nothing}[])`:

```julia
LibGEOS.createPolygon(::LinearRing)
LibGEOS.createPolygon(::Any)  # check and convert with GeoInterface if possible
LibGEOS.Polygon(::LinearRing)
LibGEOS.Polygon(::Any)  # check and convert with GeoInterface if possible
```

The `::Any` implementations should be done for other geometries as well.

**Comment by skygering** [comment]
Okay, that sounds great @evetion. The reason I want to convert from a LinearRing to a Polygon was to create a polygon from an exterior ring, basically removing any holes from a polygon. The implementation you suggested seems like a good way to do that. I will work on it.
