### ISSUE TITLE
Support for construing object using arrays 

### ISSUE THREAD

**Issue by OmriRoames** [JuliaGeo/LibGEOS.jl#23]
It would be great to have support for constructing Polygon, MultiPoints, etc from a simple Julia array.

```julia
ext_coords = [0 1 1 0 0; 0 0 1 1 0]
polygon = Polygon(ext_coords)

points = rand(2,5)
mp = MultiPolygon(points)
```

**Comment by yeesian** [comment]
Not to argue for the status quo, but what is the specific proposal here?

Should the constructors expect each row, or each column to correspond to points? Should arrays of 3 or more dimensions be supported? Should we be extending support to Vectors of Tuples, etc.

**Comment by OmriRoames** [comment]
* I think that the general convention in Julia is that each column is a point. 
* I reckon it should support 2 dimensional points and 3 if LibGEOS actually supports it. 
* I think that the most sensible thing to do is have a convenience methods for converting an Matrix of points into a vector of vectors (the current input for the constructors) and wrap the existing one.
* Support to Vectors of Tuples sounds like a good idea as well. 

I now realise that there is a big distinction between Polygon (exterior and interiors) and MultiPoints which is much simpler.

**Comment by OmriRoames** [comment]
Also, Should `Point` really have a constructor that can take a vector of any length?

**Comment by yeesian** [comment]
> Also, Should Point really have a constructor that can take a vector of any length?

Probably not. The choice to just go with vectors (versus tuples) to represent points was quite an arbitrary one. We might even go with an informal interface of "iterable" and "indexable" (rather than strictly typing the constructor). But it is not a priority for me to figure it out and implement them yet.

I'll be happy to review PRs that do not (i) unnecessarily break existing code, and (ii) arbitrarily extend support for their favorite type without effort at a solution/resolution for the wider combinatorial explosion of different types. In the meantime, the lower-level [C-facing functions](https://github.com/JuliaGeo/LibGEOS.jl/blob/efe733d9b473d8b25fe7ddb4cd688464df7e8542/src/geos_functions.jl) are already available for whoever wishes to write and maintain their own type.

**Comment by andyferris** [comment]
I think vectors of `AbstractVector`s could be useful, e.g. in combination with *StaticArrays.jl* where the abstraction is free.

**Comment by yeesian** [comment]
> I think vectors of AbstractVectors could be useful, e.g. in combination with StaticArrays.jl where the abstraction is free.

PRs welcome.
