### ISSUE TITLE
GEOS version mismatch

### ISSUE THREAD

**Issue by jaakkor2** [JuliaGeo/LibGEOS.jl#84]
Minor thing now, compat of GEOS_jll
https://github.com/JuliaGeo/LibGEOS.jl/blob/v0.6.6/Project.toml#L13
```
GEOS_jll = "3.8"
```
allows GEOS_jll update to 3.9.  Then
```
julia> LibGEOS.GEOSversion()
"3.9.0-CAPI-1.16.2"

julia> LibGEOS.GEOS_CAPI_VERSION
"3.8.0-CAPI-1.13.1"
```
Compat could be a bit more strict defining the jll version to match the library version when https://github.com/JuliaGeo/LibGEOS.jl/blob/master/gen/wrap_geos.jl was last run.  In this case
```
GEOS_jll = "~3.8"
```
That said, I am happy about the speed improvements in GEOS_jll v3.9.0+0 vs v3.8.1+0 that the present compat allows.

**Comment by visr** [comment]
Yeah there is a mismatch now, so indeed we need to rerun the wrapping script. Though since it is only a minor update, and not breaking, I'm fine with allowing the build as we do now, since it makes minor update propagate faster, since GEOS_jll is also used by GDAL_jll. What do you think?

When we rerun the wrapping script, we probably should bump the compat to 3.9 though, since new features that are newly wrapped will fail with a 3.8 build.

**Comment by jaakkor2** [comment]
I am perfectly ok with the present state (passes tests), and compat to be updated with tilde the next time GEOS is wrapped.

**Comment by visr** [comment]
I was thinking to put `GEOS_jll = "3.9"` (like [^3.9](https://julialang.github.io/Pkg.jl/v1/compatibility/)) after wrapping, such that when we get a GEOS 3.10 build, it is directly available to users of this package, and it should work since it is not breaking.
